#!/usr/bin/env bash
set -euo pipefail

git config --global user.name 'Orien Madgwick'
git config --global user.email '_@orien.io'
git config --global github.user 'orien'

git config --global core.excludesfile ~/.gitignore_global

git config --global push.default current

# set up diff-highlight
git config --global core.pager "$(brew --prefix git)/share/git-core/contrib/diff-highlight/diff-highlight | less"
git config --global color.diff-highlight.oldNormal    'red bold'
git config --global color.diff-highlight.oldHighlight 'red bold 52'
git config --global color.diff-highlight.newNormal    'green bold'
git config --global color.diff-highlight.newHighlight 'green bold 22'
