#!/usr/bin/env bash
set -euo pipefail

function stow_home {
  stow --verbose --dir=configuration --target="$HOME" $@
}

cd "$(dirname "$0")/.."

git submodule init
git submodule update

stow_home zsh
stow_home --no-folding macos
stow_home git
stow_home vim
stow_home spacemacs
stow_home ruby

vim '+call minpac#update()' +quitall
