#!/usr/bin/env bash
set -euo pipefail

function stow_home {
  stow --verbose --dir=configuration --target="$HOME" $@
}

cd "$(dirname "$0")/.."

git submodule init
git submodule update

which -s stow || {
  if (which -s brew); then
    brew install stow
  else
    echo "Missing GNU stow; please install it then re-run $0"
    exit 1
  fi
}

stow_home zsh
stow_home --no-folding macos
stow_home git
stow_home vim
stow_home spacemacs
stow_home lang

vim '+call minpac#update()' +quitall
