tap 'homebrew/cask-versions'

# tap 'sj26/git-buildkite'
# brew 'sj26/git-buildkite/git-buildkite'

brew 'cabal-install'
brew 'dos2unix'
brew 'ghc'
brew 'gist'
brew 'git'
brew 'haskell-stack'
brew 'hub'
brew 'pidof'
brew 'pv'
brew 'python'
brew 'sqlite'

cask 'alfred'
cask 'dash'
cask 'docker'
cask 'dropbox'
cask 'flux'
cask 'imageoptim'
cask 'iTerm2'
cask 'karabiner-elements' # I like to map the caps lock key to escape
cask 'muzzle'
cask 'shortcat'
cask 'slack'
cask 'sourcetree'

# Shells
brew 'dash'
brew 'zsh'

# Editors
tap 'railwaycat/emacsmacport'
cask 'railwaycat/emacsmacport/emacs-mac'
brew 'vim'
cask 'visual-studio-code'

# Text Search
brew 'ctags'
brew 'fzf'
brew 'lesspipe'
brew 'ripgrep'

# AWS and Infrastructure
cask 'aws-vault'
brew 'awscli'
brew 'iamy'
brew 'packer'

# Web Development
brew 'chromedriver'
brew 'elm'
brew 'libxml2'
brew 'nginx'
brew 'nodenv'

# Networking
brew 'curl'
brew 'dnsmasq'
brew 'nmap'
brew 'wget'

# Archiving and Compression
brew 'gnu-tar'
brew 'unrar'

# Web Browsers
cask 'firefoxdeveloperedition'
cask 'google-chrome'
cask 'vivaldi'

# Go Ecosystem
brew 'go'

# Ruby Ecosystem
brew 'rbenv'

# Java Ecosystem
cask 'java'
brew 'maven'

# Documentation and Diagramming
brew 'graphviz'
brew 'ispell'
brew 'pandoc'
brew 'plantuml'

# Encryption tools
brew 'gpg2'
cask 'keybase'

# SQL
cask 'datagrip'

# Drivers
tap 'homebrew/cask-drivers'
cask 'logitech-control-center'

# Fonts
tap 'homebrew/cask-fonts'
cask 'font-inconsolata'
cask 'font-source-code-pro'
