tap 'homebrew/cask-versions'

# tap 'railwaycat/emacsmacport'
# cask "railwaycat/emacsmacport/emacs-mac"

# tap 'sj26/git-buildkite'
# brew 'sj26/git-buildkite/git-buildkite'

brew 'awscli'
brew 'chromedriver'
brew 'ctags'
brew 'cabal-install'
brew 'curl'
brew 'dash'
brew 'dnsmasq'
brew 'dos2unix'
brew 'elm'
brew 'fzf'
brew 'ghc'
brew 'gist'
brew 'git'
brew 'gnu-tar'
brew 'graphviz'
brew 'haskell-stack'
brew 'hub'
brew 'iamy'
brew 'ispell'
brew 'lesspipe'
brew 'libxml2'
brew 'nginx'
brew 'nmap'
brew 'nodenv'
brew 'packer'
brew 'pandoc'
brew 'pidof'
brew 'pv'
brew 'python'
brew 'ripgrep'
brew 'sqlite'
brew 'unrar'
brew 'vim'
brew 'wget'
brew 'zsh'

cask 'alfred'
cask 'aws-vault'
cask 'dash'
cask 'docker'
cask 'dropbox'
cask 'flux'
cask 'grammarly'
cask 'imageoptim'
cask 'iTerm2'
cask 'karabiner-elements' # I like to map the caps lock key to escape
cask 'muzzle'
cask 'shortcat'
cask 'slack'
cask 'sourcetree'
cask 'visual-studio-code'

# Web Browsers
cask 'firefoxdeveloperedition'
cask 'google-chrome'
cask 'vivaldi'

# Go Ecosystem
brew 'go'

# Ruby Ecosystem
brew 'rbenv'

# Java Ecosystem
cask 'java'
brew 'maven'
brew 'plantuml'

# Encryption tools
brew 'gpg2'
cask 'keybase'

cask 'datagrip'

# Drivers
tap 'homebrew/cask-drivers'
cask 'logitech-control-center'
