set nocompatible
set encoding=utf-8

execute pathogen#infect()

Helptags

" Setup visuals
syntax on
filetype plugin indent on
set list
set number
set laststatus=2

" powerline HUD
let g:Powerline_symbols = 'fancy'
let g:Powerline_theme = 'default'
let g:Powerline_colorscheme = 'solarized16'

" solarized colour scheme
set background=dark
let g:solarized_visibility='low'
colorscheme solarized

" change cursor in insert mode (iterm2)
autocmd InsertEnter * set cul
autocmd InsertLeave * set nocul
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

" formating
set ts=2 sts=2 sw=2 expandtab

" Use Z Shell with profile
set shell=zsh\ -l
