set nocompatible
set encoding=utf-8
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

Bundle       'rking/ag.vim'
Bundle        'kien/ctrlp.vim'
Bundle    'rizzatti/dash.vim'
Bundle      'sjbach/lusty'
Bundle 'jimenezrick/vimerl'
Bundle       'bling/vim-airline'
Bundle       'tpope/vim-bundler'
Bundle       'tpope/vim-classpath'
Bundle        'guns/vim-clojure-static'
Bundle      'kchmck/vim-coffee-script'
Bundle 'altercation/vim-colors-solarized'
Bundle       'tpope/vim-commentary'
Bundle       'tpope/vim-cucumber'
Bundle 'elixir-lang/vim-elixir'
Bundle       'tpope/vim-endwise'
Bundle       'tpope/vim-fireplace'
Bundle       'tpope/vim-fugitive'
Bundle       'tpope/vim-haml'
Bundle       'tpope/vim-markdown'
Bundle      'rodjek/vim-puppet'
Bundle       'tpope/vim-rails'
Bundle       'tpope/vim-rake'
Bundle       'tpope/vim-rbenv'
Bundle    'vim-ruby/vim-ruby'
Bundle  'derekwyatt/vim-scala'
Bundle    'goldfeld/vim-seek'
Bundle       'tpope/vim-sensible'
Bundle       'tpope/vim-surround'

set hidden

" integrate with the mouse
set mouse=a

" setup visuals
syntax on
filetype plugin indent on
set list
set number
set laststatus=2

" searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" airline HUD
let g:airline_powerline_fonts = 0
let g:airline_enable_branch = 1
let g:airline_detect_modified = 1
let g:airline_left_sep = ' '
let g:airline_right_sep = ' '
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme = 'tomorrow'

" bufferline
let g:bufferline_echo=0

" colour scheme
set background=dark
" let g:solarized_visibility='low'
" colorscheme solarized
let base16colorspace=256
colorscheme base16-railscasts

" change cursor in insert mode (iterm2)
autocmd InsertEnter * set cul
autocmd InsertLeave * set nocul
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

" formating
set ts=2 sts=2 sw=2 expandtab

" Use Z Shell with profile
set shell=zsh\ -l

" ruby
let ruby_no_expensive = 1
autocmd FileType ruby let g:rubycomplete_buffer_loading = 1
autocmd FileType ruby let g:rubycomplete_classes_in_global = 1
autocmd FileType ruby let g:rubycomplete_rails = 1

