#========= Oh My ZSH config =========

ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"
DEFAULT_USER="orien"
DISABLE_AUTO_UPDATE="true"
DISABLE_CORRECTION="true"

plugins=(brew rbenv gem git capistrano gem lein rails redis-cli vagrant)

source $ZSH/oh-my-zsh.sh

#========= some more jazz =========

[[ -f /opt/boxen/env.sh ]] && source /opt/boxen/env.sh
export EDITOR=vim
BREW_PREFIX=`brew --prefix`
alias lessc=$BREW_PREFIX/share/vim/vim74/macros/less.sh
export LESSOPEN="|$BREW_PREFIX/bin/lesspipe.sh %s" # Enable the lesspipe http://www-zeuthen.desy.de/~friebel/unix/lesspipe.html
export PATH="$HOME/bin:$PATH"
export VAGRANT_DEFAULT_PROVIDER=vmware_fusion
